server:
  port: 8090

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: firstModule
        uri: http://localhost:8081/
        predicates:
        - Path=/first/**
        filters:
        - AddRequestHeader=first-request, first-request-header
        - AddResponseHeader=first-response, first-response-header
      - id: secondModule
        uri: http://localhost:8082/
        predicates:
        - Path=/second/**
        filters:
        - AddRequestHeader=second-request, second-request-header
        - AddResponseHeader=second-response, second-response-header